package com.housing.ownertenantapi.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;

@Schema(description = "OAuth login request for Google or Apple sign-in")
public record OAuthLoginRequest(
    @Schema(description = "Authorization code returned by the provider when using an authorization-code flow", example = "oauth_code_123")
    String authorizationCode,
    @Schema(description = "PKCE code verifier generated by the frontend for the authorization-code flow", example = "Q5M3m1m4aKYc5qG7vVx0Y2w1bB8lR4w2uN6pS9dH7tL")
    String codeVerifier,
    @Schema(description = "Identity token returned by Google Identity Services when using the browser sign-in button", example = "eyJhbGciOiJSUzI1NiIsImtpZCI6I...")
    String identityToken,
    @Schema(description = "Frontend redirect URI used in the OAuth flow", example = "https://app.example.com/auth/callback")
    @NotBlank
    String redirectUri
) {
}
